services:
    discord-latex-bot:
        build:
            context: .
        container_name: discord-latex-bot
        restart: "no"
        secrets:
          - discord_token

secrets:
    discord_token:
        file: ./secrets/discord_token.txt
